more improved groovyserver shellscript
- made a reason of error understandable easily (for environmental debugging)
- echo resolved GROOVYSERV_HOME
- to use GROOVYSERV_HOME which was resolved by new implemention when resolving GROOVYCLIENT_CMD

diff --git a/src/main/bin/groovyserver b/src/main/bin/groovyserver
--- a/src/main/bin/groovyserver
+++ b/src/main/bin/groovyserver
@@ -81,74 +81,13 @@ elif [ "x$GROOVY_HOME" != "x" ]; then
         export GROOVY_HOME=`cygpath -u "$GROOVY_HOME"`
     fi
     GROOVY_BIN="$GROOVY_HOME/bin/groovy"
+    if [ ! -x "$GROOVY_BIN" ]; then
+        echo "ERROR: Not found a valid groovy command in GROOVY_HOME: $GROOVY_BIN"
+        exit 1
+    fi
 else
     echo "ERROR: Not found a groovy command. Required either PATH having groovy command or GROOVY_HOME"
     exit 1
-fi
-
-#-------------------------------------------
-# Setup variables
-#-------------------------------------------
-
-if $OS_CYGWIN; then
-  USER_HOME=`cygpath -u "$USERPROFILE"`
-  export JAVA_HOME=`cygpath -u "$JAVA_HOME"`
-fi
-
-GROOVYSERV_WORK_DIR=${USER_HOME:-$HOME}/.groovy/groovyserv
-if [ ! -d "$GROOVYSERV_WORK_DIR" ]; then
-    mkdir -p "$GROOVYSERV_WORK_DIR"
-fi
-
-PORT=${GROOVYSERVER_PORT:-1961}
-GROOVYSERV_OPTS="$GROOVYSERV_OPTS -Dgroovyserver.port=$PORT"
-
-GROOVYSERV_PID_FILE="$GROOVYSERV_WORK_DIR/pid-$PORT"
-GROOVYSERV_COOKIE_FILE="$GROOVYSERV_WORK_DIR/cookie"
-
-GROOVYCLIENT_CMD="${GROOVYSERV_HOME:-"`dirname $0`/.."}/bin/groovyclient"
-IS_SERVER_AVAILABLE="env GROOVYSERVER_PORT=$PORT $GROOVYCLIENT_CMD --without-invoking-server -e \"\""
-EXPIRED_PID_FILE="( cd \"$GROOVYSERV_WORK_DIR\" && find . -name pid-$PORT -mmin +1 )"
-
-#-------------------------------------------
-# Kill process if specified
-#-------------------------------------------
-
-if [ "$DO_KILL" != "" ]; then
-    if [ -f "$GROOVYSERV_PID_FILE" ]; then
-        EXISTED_PID=`cat "$GROOVYSERV_PID_FILE"`
-        kill -9 $EXISTED_PID
-        echo "Killed groovyserver of $EXISTED_PID($PORT)"
-        rm -f "$GROOVYSERV_PID_FILE"
-        rm -f "$GROOVYSERV_COOKIE_FILE"
-    else
-        echo "PID file $GROOVYSERV_PID_FILE not found"
-    fi
-    if [ "$DO_KILL" = "KILL_ONLY" ]; then
-        exit 0
-    fi
-    echo "Restarting groovyserver"
-fi
-
-#-------------------------------------------
-# Check duplicated invoking
-#-------------------------------------------
-
-if [ -f "$GROOVYSERV_PID_FILE" ]; then
-    EXISTED_PID=`cat "$GROOVYSERV_PID_FILE"`
-
-    # if connecting to server is succeed, return with warning message
-    $IS_SERVER_AVAILABLE > /dev/null 2>&1
-    if [ $? -eq 0 ]; then
-        echo "WARN: groovyserver is already running as $EXISTED_PID($PORT)"
-        exit 1
-    fi
-
-    # if PID file doesn't expired, terminate the sequence of invoking server
-    if [ "`sh -c \"$EXPIRED_PID_FILE\"`" = "" ]; then
-        echo "WARN: Another process may be starting groovyserver."
-        exit 1
-    fi
 fi
 
 #-------------------------------------------
@@ -198,23 +137,93 @@ if [ ! $? -eq 0 ]; then
     echo "ERROR: Not found a valid GROOVYSERV_HOME directory: $GROOVYSERV_HOME"
     exit 1
 fi
+echo "GROOVYSERV_HOME: $GROOVYSERV_HOME"
+
+#-------------------------------------------
+# Setup variables
+#-------------------------------------------
+
+if $OS_CYGWIN; then
+  USER_HOME=`cygpath -u "$USERPROFILE"`
+  export JAVA_HOME=`cygpath -u "$JAVA_HOME"`
+fi
+
+GROOVYSERV_WORK_DIR=${USER_HOME:-$HOME}/.groovy/groovyserv
+if [ ! -d "$GROOVYSERV_WORK_DIR" ]; then
+    mkdir -p "$GROOVYSERV_WORK_DIR"
+fi
+
+PORT=${GROOVYSERVER_PORT:-1961}
+GROOVYSERV_OPTS="$GROOVYSERV_OPTS -Dgroovyserver.port=$PORT"
+
+GROOVYSERV_PID_FILE="$GROOVYSERV_WORK_DIR/pid-$PORT"
+GROOVYSERV_COOKIE_FILE="$GROOVYSERV_WORK_DIR/cookie"
+
+GROOVYCLIENT_CMD="$GROOVYSERV_HOME/bin/groovyclient"
+IS_SERVER_AVAILABLE="env GROOVYSERVER_PORT=$PORT $GROOVYCLIENT_CMD --without-invoking-server -e \"\""
+EXPIRED_PID_FILE="( cd \"$GROOVYSERV_WORK_DIR\" && find . -name pid-$PORT -mmin +1 )"
+
+export CLASSPATH="$CP:$GROOVYSERV_HOME/lib/*"
+
+#-------------------------------------------
+# Kill process if specified
+#-------------------------------------------
+
+if [ "$DO_KILL" != "" ]; then
+    if [ -f "$GROOVYSERV_PID_FILE" ]; then
+        EXISTED_PID=`cat "$GROOVYSERV_PID_FILE"`
+        kill -9 $EXISTED_PID
+        echo "Killed groovyserver of $EXISTED_PID($PORT)"
+        rm -f "$GROOVYSERV_PID_FILE"
+        rm -f "$GROOVYSERV_COOKIE_FILE"
+    else
+        echo "PID file $GROOVYSERV_PID_FILE not found"
+    fi
+    if [ "$DO_KILL" = "KILL_ONLY" ]; then
+        exit 0
+    fi
+    echo "Restarting groovyserver"
+fi
+
+#-------------------------------------------
+# Check duplicated invoking
+#-------------------------------------------
+
+if [ -f "$GROOVYSERV_PID_FILE" ]; then
+    EXISTED_PID=`cat "$GROOVYSERV_PID_FILE"`
+
+    # if connecting to server is succeed, return with warning message
+    $IS_SERVER_AVAILABLE > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        echo "WARN: groovyserver is already running as $EXISTED_PID($PORT)"
+        exit 1
+    fi
+
+    # if PID file doesn't expired, terminate the sequence of invoking server
+    if [ "`sh -c \"$EXPIRED_PID_FILE\"`" = "" ]; then
+        echo "WARN: Another process may be starting groovyserver."
+        exit 1
+    fi
+fi
 
 #-------------------------------------------
 # Invoke server
 #-------------------------------------------
 
-export CLASSPATH=$CP:$GROOVYSERV_HOME/lib/*
 nohup "$GROOVY_BIN" $GROOVYSERV_OPTS -e "org.jggug.kobo.groovyserv.GroovyServer.main(args)" > /dev/null 2>&1 &
 
 #-------------------------------------------
 # Store PID
 #-------------------------------------------
 
+sleep 1
 PID=$!
 if ps -p $PID | grep $PID > /dev/null; then
     echo $PID > "$GROOVYSERV_PID_FILE"
 else
     echo "ERROR: Failed to store PID into file $GROOVYSERV_PID_FILE"
+    echo "Rerun for debug..."
+    "$GROOVY_BIN" $GROOVYSERV_OPTS -e "org.jggug.kobo.groovyserv.GroovyServer.main(args)" &
     exit 1
 fi
 
