improved starting sequence of groovyserver by groovyserver shell script
- waiting until groovyserver has started up

diff --git a/src/main/bin/groovyserver b/src/main/bin/groovyserver
--- a/src/main/bin/groovyserver
+++ b/src/main/bin/groovyserver
@@ -20,8 +20,13 @@
 #-------------------------------------------
 
 if [ "x$GROOVY_HOME" = "x" ]; then
-    echo "environment variable GROOVY_HOME must be set."
+    echo "ERROR: Environment variable GROOVY_HOME must be set."
     exit 1
+fi
+
+PORT=1961
+if [ "$GROOVYSERVER_PORT" != "" ]; then
+    export PORT=$GROOVYSERVER_PORT
 fi
 
 GROOVYSERV_WORK_DIR=~/.groovy/groovyserv
@@ -29,10 +34,12 @@ if [ ! -d "$GROOVYSERV_WORK_DIR" ]; then
     mkdir -p "$GROOVYSERV_WORK_DIR"
 fi
 
-PORT=1961
-if [ "$GROOVYSERVER_PORT" != "" ]; then
-    export PORT=$GROOVYSERVER_PORT
-fi
+GROOVYSERV_PID_FILE="$GROOVYSERV_WORK_DIR/pid-$PORT"
+GROOVYSERV_COOKIE_FILE="$GROOVYSERV_WORK_DIR/cookie"
+
+GROOVYCLIENT_CMD="${GROOVYSERV_HOME:-"`dirname $0`/.."}/bin/groovyclient"
+IS_SERVER_AVAILABLE="$GROOVYCLIENT_CMD --without-invoking-server -v"
+EXPIRED_PID_FILE="find $GROOVYSERV_PID_FILE -mmin +1"
 
 #-------------------------------------------
 # Handle arguments
@@ -55,19 +62,19 @@ while [ $# -gt 0 ]; do
             shift
             ;;
         -[kr])
-            GROOVYSERV_PID_FILE="$GROOVYSERV_WORK_DIR/pid-$PORT"
             if [ -f "$GROOVYSERV_PID_FILE" ]; then
-                PID=`cat "$GROOVYSERV_PID_FILE"`
-                kill -9 $PID
-                echo "kill groovy server $PID($PORT)"
-                rm "$GROOVYSERV_PID_FILE"
+                EXISTED_PID=`cat "$GROOVYSERV_PID_FILE"`
+                kill -9 $EXISTED_PID
+                echo "Killed groovyserver of $EXISTED_PID($PORT)"
+                rm -f "$GROOVYSERV_PID_FILE"
+                rm -f "$GROOVYSERV_COOKIE_FILE"
             else
-                echo "pid file $GROOVYSERV_PID_FILE not found"
+                echo "PID file $GROOVYSERV_PID_FILE not found"
             fi
             if [ "$1" = "-k" ]; then
                 exit 0
             fi
-            echo "restart groovy server"
+            echo "Restarting groovyserver"
             shift
             ;;
         *)
@@ -87,20 +94,19 @@ done
 # Check multi invoking
 #-------------------------------------------
 
-GROOVYSERV_PID_FILE="$GROOVYSERV_WORK_DIR/pid-$PORT"
 if [ -f "$GROOVYSERV_PID_FILE" ]; then
-    if [ "`find \"$GROOVYSERV_PID_FILE\" -mmin -30`" != "" ] ; then
-        echo "starting server by another session..."
-        exit 2
+    EXISTED_PID=`cat "$GROOVYSERV_PID_FILE"`
+
+    # if connecting to server is succeed, return successfully
+    $IS_SERVER_AVAILABLE > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        echo "WARN: groovyserver is already running as $EXISTED_PID($PORT)"
+        exit 1
     fi
-    PID=`cat "$GROOVYSERV_PID_FILE"`
-    if ! ps -p $PID | grep $PID > /dev/null; then
-        rm "$GROOVYSERV_PID_FILE"
-    else
-        echo "ERROR: Groovy server already running, pid is $PID."
-        echo "To kill the server, run \"groovyserver -k\"."
-        echo "If groovy server does not ruuning actually,"
-        echo "retry after removing file $GROOVYSERV_PID_FILE."
+
+    # if PID file doesn't expired, terminate invoking server
+    if [ "`$EXPIRED_PID_FILE`" = "" ]; then
+        echo "WARN: Another process may be starting groovyserver."
         exit 1
     fi
 fi
@@ -125,9 +131,36 @@ PID=$!
 if ps -p $PID | grep $PID > /dev/null; then
     echo $PID > "$GROOVYSERV_PID_FILE"
 else
-    echo "ERROR: cannot store PID to file $GROOVYSERV_PID_FILE"
+    echo "ERROR: Failed to store PID into file $GROOVYSERV_PID_FILE"
     exit 1
 fi
 
-echo "groovy server $PID($PORT) is successfully started."
+#-------------------------------------------
+# Wait for available
+#-------------------------------------------
+
+while TRUE; do
+    echo -n "."
+    sleep 1
+
+    # waiting until cookie filed is created
+    if [ ! -f "$GROOVYSERV_COOKIE_FILE" ]; then
+        continue
+    fi
+
+    # if connecting to server is succeed, return successfully
+    $IS_SERVER_AVAILABLE > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        break
+    fi
+
+    # if PID file was expired while to connect to server is failing, error
+    if [ "`$EXPIRED_PID_FILE`" != "" ]; then
+        echo "ERROR: Timeout. Confirm if groovyserver $PID($PORT) is running."
+        exit 1
+    fi
+done
+
+echo
+echo "groovyserver $PID($PORT) is successfully started"
 
